version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql4fedml
    restart: always
    volumes:
        ## 数据库初始化文件
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fedml
    ports:
    - 3306:3306
  fedml4web:
    image: fedml4web          # 自己封装jar包的镜像
    container_name: fedml4web
    volumes:
    -                         # 配置好磁盘映射，到时可通过相对路径查找到服务器本地文件，也可使用绝对路径
    ports:
    - 8081:8081